### ISSUE TITLE
[Bug]: Empty Toolbar appears when the app should start with no Terminal Toolbar

### ISSUE THREAD

**Issue by h0tk3y** [Termux-Monet/termux-monet#172]
### Problem description

The app shows a semi-transparent overlay with no meaningful content in place of the Terminal Toolbar whenever it should start with no Terminal Toolbar.

This overlay obscured the terminal content behind it. It is possible to get rid of the overlay by enabling and disabling the Terminal Overlay again. When you "enable" it, the overlay starts showing meaningful content. After that, "disabling" it makes the overlay properly disappear.

![Screenshot_20240825_013244_TermuxMonet](https://github.com/user-attachments/assets/ba6a9efa-e518-4aaf-aeb5-783da571aebf)

### Steps to reproduce the behavior.

1. Disable the Terminal Toolbar, e.g. by pressing VolumeUp+Q
2. Close the app
3. Open the app again 
4. The empty semi-transparent overlay will appear until you toggle the Terminal Toolbar

### What is the expected behavior?

When the app is closed with Terminal Toolbar hidden, it should not show the Terminal Toolbar or the empty overlay in its place on next launch. 

### System information

* Termux Monet version: v0.119.0-b1-36, 0.119.0-b1+monet36.ff13243. 
* Is Nightly or Stable?: both
* Android OS version: 14
* Device model: Samsung Galaxy S23 Ultra

**Comment by h0tk3y** [comment]
Turning off `Extra Keys Blurred Background` in the settings does not fix the issue. Instead, the empty overlay just becomes non-transparent.

**Comment by h0tk3y** [comment]
A workaround I found is disabling the extra keys altogether with `extra-keys = []` in `termux.properties`. However, I'd like to still use the extra keys in some cases.

**Comment by KitsunedFox** [comment]
Fixed on latest nightly builds. You can download the artifacts with this bug fixed. https://github.com/Termux-Monet/termux-monet/actions/runs/10586245950

**Comment by h0tk3y** [comment]
@KitsunedFox I tried the latest nightly. The issue I reported is gone indeed, but there seems to be another: when the IME is shown, the layout is incorrectly measured, and the terminal shrinks above a huge offset. See the screenshots
![Screenshot_20240828_030009_TermuxMonet](https://github.com/user-attachments/assets/2a5ef189-62cb-4adc-b330-2277cf20dd33)
![Screenshot_20240828_030123_TermuxMonet](https://github.com/user-attachments/assets/2788000d-2258-4c44-8b41-869d066d492c)
