### ISSUE TITLE
Annoying button to enter password appears above the keyboard.

### ISSUE THREAD

**Issue by Dhyfer1** [Termux-Monet/termux-monet#175]
### Problem description

Hi @KitsunedFox

The problem is that now a password button appears above the keyboard, this button you see in the screenshot also appears in termux stable and beta from the official repository, but the problem was fixed with the latest build action.

![Screenshot_20240826-093310](https://github.com/user-attachments/assets/0c30316d-fccd-431d-850f-e0878170e713)

In the official repository of termux-app there is an [issue](https://github.com/termux/termux-app/issues/3909) talking about the same problem, but it was already fixed with the last build action, as mentioned [here](https://github.com/termux/termux-app/issues/3909#issuecomment-2311306938)

I hope you can fix it too, it's really annoying to see this button every time I open termux monet

### Steps to reproduce the behavior.

After a clean install of termux monet, this button appears after some time of using the app or when I return to termux monet after using another app 

### What is the expected behavior?

I just don't want this button to appear if I don't need it.

### System information

* Termux Monet version: v0.119.0-b1-36
* Is Nightly or Stable?: Latest version in release: Update Flavor
* Android OS version: 14
* Device model: Tecno Pova 5 
*

**Comment by KitsunedFox** [comment]
Fixed on latest nightly build. just had to merge recent changes from upstream. https://github.com/Termux-Monet/termux-monet/actions/runs/10584765018

**Comment by Dhyfer1** [comment]
Thank you very much for responding quickly. I have installed the last nightly build and that button no longer appears, thanks for that. I hope the fix will come soon to the next stable release.
